package com.example.control

import android.accessibilityservice.AccessibilityService
import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Intent
import android.os.Build
import android.os.Handler
import android.os.Looper
import android.util.Log
import android.view.accessibility.AccessibilityEvent
import android.view.accessibility.AccessibilityNodeInfo

class ControlAccessibilityService : AccessibilityService() {

    private var lastBlockedPackage: String? = null
    private var lastContentScanTime = 0L
    private val contentScanThrottleMs = 800L

    override fun onServiceConnected() {
        super.onServiceConnected()
        Log.d("ControlService", "Serviço de acessibilidade CONECTADO e rodando.")
        startAsForeground()
    }

    override fun onAccessibilityEvent(event: AccessibilityEvent?) {
        val packageName = event?.packageName?.toString() ?: return

        if (packageName != lastBlockedPackage) {
            lastBlockedPackage = null
        }

        if (lastBlockedPackage == packageName) return

        if (BlockedApps.isBlocked(packageName)) {
            Log.d("ControlService", "App bloqueado (lista): $packageName")
            lastBlockedPackage = packageName
            interceptAndOpenCrisisScreen(packageName)
            return
        }

        if (TrustedApps.isTrusted(packageName)) return

        if (SuspiciousPackages.looksAutoGenerated(packageName)) {
            Log.d("ControlService", "Nome de pacote suspeito detectado: $packageName")
            lastBlockedPackage = packageName
            interceptAndOpenCrisisScreen(packageName)
            return
        }

        val now = System.currentTimeMillis()
        if (now - lastContentScanTime < contentScanThrottleMs) return
        lastContentScanTime = now

        if (screenContainsGamblingContent(packageName)) {
            Log.d("ControlService", "Conteúdo de aposta detectado na tela de: $packageName")
            lastBlockedPackage = packageName
            interceptAndOpenCrisisScreen(packageName)
        }
    }

    private fun screenContainsGamblingContent(packageName: String): Boolean {
        if (!BrowserPackages.isBrowser(packageName)) return false

        val root = rootInActiveWindow ?: return false
        return try {
            val urlText = findAddressBarText(root, depth = 0)
            GamblingKeywords.containsGamblingKeyword(urlText) ||
                SuspiciousUrls.containsSuspiciousDomain(urlText) ||
                SuspiciousUrls.containsRawIpAddress(urlText)
        } catch (e: Exception) {
            Log.d("ControlService", "Erro ao varrer conteúdo da tela: ${e.message}")
            false
        }
    }

    private fun findAddressBarText(node: AccessibilityNodeInfo?, depth: Int): String? {
        if (node == null || depth > 50) return null

        val resourceId = node.viewIdResourceName
        if (resourceId != null &&
            (resourceId.contains("url_bar") ||
                resourceId.contains("location_bar") ||
                resourceId.contains("toolbar_url"))
        ) {
            val collected = StringBuilder()
            collectAllText(node, collected, depth = 0)
            return collected.toString().ifBlank { null }
        }

        for (i in 0 until node.childCount) {
            val found = findAddressBarText(node.getChild(i), depth + 1)
            if (found != null) return found
        }
        return null
    }

    private fun collectAllText(node: AccessibilityNodeInfo?, out: StringBuilder, depth: Int) {
        if (node == null || depth > 20) return
        node.text?.let { out.append(it).append(' ') }
        node.contentDescription?.let { out.append(it).append(' ') }
        for (i in 0 until node.childCount) {
            collectAllText(node.getChild(i), out, depth + 1)
        }
    }

    private fun tryCloseCurrentTab(): Boolean {
        val root = rootInActiveWindow ?: return false
        val closeTabNode = findCloseTabNode(root, depth = 0) ?: return false
        return closeTabNode.performAction(AccessibilityNodeInfo.ACTION_CLICK)
    }

    private fun findCloseTabNode(node: AccessibilityNodeInfo?, depth: Int): AccessibilityNodeInfo? {
        if (node == null || depth > 50) return null

        val description = node.contentDescription?.toString()?.lowercase()
        if (description != null &&
            (description.contains("fechar aba") || description.contains("close tab"))
        ) {
            return node
        }

        for (i in 0 until node.childCount) {
            val found = findCloseTabNode(node.getChild(i), depth + 1)
            if (found != null) return found
        }
        return null
    }

    private fun interceptAndOpenCrisisScreen(packageName: String) {
        val isBrowser = BrowserPackages.isBrowser(packageName)
        val handler = Handler(Looper.getMainLooper())

        if (isBrowser) {
            val tabClosed = tryCloseCurrentTab()
            Log.d("ControlService", "[navegador] Tentativa de fechar aba: $tabClosed")

            handler.postDelayed({ performGlobalAction(GLOBAL_ACTION_BACK) }, 3000)
            handler.postDelayed({ performGlobalAction(GLOBAL_ACTION_HOME) }, 3500)
        } else {
            performGlobalAction(GLOBAL_ACTION_HOME)
        }

        val intent = Intent(this, MainActivity::class.java).apply {
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP)
            putExtra(EXTRA_OPEN_CRISIS, true)
        }
        startActivity(intent)
    }

    private fun startAsForeground() {
        val channelId = "control_protection_channel"

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channel = NotificationChannel(
                channelId,
                "Proteção ativa",
                NotificationManager.IMPORTANCE_LOW
            ).apply {
                description = "Mostra que o Control está monitorando ativamente."
            }
            val manager = getSystemService(NotificationManager::class.java)
            manager.createNotificationChannel(channel)
        }

        val contentIntent = PendingIntent.getActivity(
            this, 0,
            Intent(this, MainActivity::class.java),
            PendingIntent.FLAG_IMMUTABLE
        )

        val notification: Notification = Notification.Builder(this, channelId)
            .setContentTitle("Control está ativo")
            .setContentText("Protegendo você de apps e sites de apostas.")
            .setSmallIcon(android.R.drawable.ic_lock_lock)
            .setContentIntent(contentIntent)
            .setOngoing(true)
            .build()

        try {
            startForeground(NOTIFICATION_ID, notification)
        } catch (e: Exception) {
            Log.d("ControlService", "Não foi possível exibir notificação: ${e.message}")
        }
    }

    override fun onInterrupt() {}

    companion object {
        const val EXTRA_OPEN_CRISIS = "open_crisis"
        const val NOTIFICATION_ID = 1001
    }
}