package com.example.control

object SuspiciousPackages {
    private const val MIN_SEGMENT_LENGTH = 5

    fun looksAutoGenerated(packageName: String?): Boolean {
        if (packageName.isNullOrBlank()) return false

        val segments = packageName.split(".")
        for (segment in segments) {
            if (segment.length < MIN_SEGMENT_LENGTH) continue
            val hasDigit = segment.any { it.isDigit() }
            val hasLetter = segment.any { it.isLetter() }
            if (hasDigit && hasLetter) return true
        }
        return false
    }
}